### ISSUE TITLE
奇幻旅程1737 星期天

### ISSUE THREAD

**Issue by abearxiong** [abearxiong/abearxiong.github.io#113]
真是开心啊

document.documentElement.style属性定义了当前浏览器支持的所有css属性

```javascript
function support(cssName) {
    var htmlStyle = document.documentElement.style;
    if (cssName in htmlStyle)
        return true;
    return false;
}
alert(support(‘animate‘)); //false
alert(support(‘animation‘)); //true
```

```css
html{font-size:10px}
@media screen and (min-width:321px) and (max-width:375px){html{font-size:11px}}
@media screen and (min-width:376px) and (max-width:414px){html{font-size:12px}}
@media screen and (min-width:415px) and (max-width:639px){html{font-size:15px}}
@media screen and (min-width:640px) and (max-width:719px){html{font-size:20px}}
@media screen and (min-width:720px) and (max-width:749px){html{font-size:22.5px}}
@media screen and (min-width:750px) and (max-width:799px){html{font-size:23.5px}}
@media screen and (min-width:800px){html{font-size:25px}}
```
